################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../activemasternode.cpp \
../addrman.cpp \
../alert.cpp \
../amount.cpp \
../arith_uint256.cpp \
../base58.cpp \
../bloom.cpp \
../chain.cpp \
../chainparams.cpp \
../chainparamsbase.cpp \
../checkpoints.cpp \
../clientversion.cpp \
../coins.cpp \
../compressor.cpp \
../core_read.cpp \
../core_write.cpp \
../darksend-relay.cpp \
../darksend.cpp \
../dbwrapper.cpp \
../dsnotificationinterface.cpp \
../governance-classes.cpp \
../governance-object.cpp \
../governance-vote.cpp \
../governance-votedb.cpp \
../governance.cpp \
../hash.cpp \
../httprpc.cpp \
../httpserver.cpp \
../init.cpp \
../instantx.cpp \
../keepass.cpp \
../key.cpp \
../keystore.cpp \
../main.cpp \
../masternode-payments.cpp \
../masternode-sync.cpp \
../masternode.cpp \
../masternodeconfig.cpp \
../masternodeman.cpp \
../merkleblock.cpp \
../miner.cpp \
../net.cpp \
../netbase.cpp \
../netfulfilledman.cpp \
../noui.cpp \
../pow.cpp \
../protocol.cpp \
../pubkey.cpp \
../random.cpp \
../rest.cpp \
../rpcblockchain.cpp \
../rpcclient.cpp \
../rpcgovernance.cpp \
../rpcmasternode.cpp \
../rpcmining.cpp \
../rpcmisc.cpp \
../rpcnet.cpp \
../rpcprotocol.cpp \
../rpcrawtransaction.cpp \
../rpcserver.cpp \
../scheduler.cpp \
../sendalert.cpp \
../spork.cpp \
../sprint-cli.cpp \
../sprint-tx.cpp \
../sprintd.cpp \
../sync.cpp \
../timedata.cpp \
../torcontrol.cpp \
../txdb.cpp \
../txmempool.cpp \
../uint256.cpp \
../util.cpp \
../utilmoneystr.cpp \
../utilstrencodings.cpp \
../utiltime.cpp \
../validationinterface.cpp \
../versionbits.cpp 

OBJS += \
./activemasternode.o \
./addrman.o \
./alert.o \
./amount.o \
./arith_uint256.o \
./base58.o \
./bloom.o \
./chain.o \
./chainparams.o \
./chainparamsbase.o \
./checkpoints.o \
./clientversion.o \
./coins.o \
./compressor.o \
./core_read.o \
./core_write.o \
./darksend-relay.o \
./darksend.o \
./dbwrapper.o \
./dsnotificationinterface.o \
./governance-classes.o \
./governance-object.o \
./governance-vote.o \
./governance-votedb.o \
./governance.o \
./hash.o \
./httprpc.o \
./httpserver.o \
./init.o \
./instantx.o \
./keepass.o \
./key.o \
./keystore.o \
./main.o \
./masternode-payments.o \
./masternode-sync.o \
./masternode.o \
./masternodeconfig.o \
./masternodeman.o \
./merkleblock.o \
./miner.o \
./net.o \
./netbase.o \
./netfulfilledman.o \
./noui.o \
./pow.o \
./protocol.o \
./pubkey.o \
./random.o \
./rest.o \
./rpcblockchain.o \
./rpcclient.o \
./rpcgovernance.o \
./rpcmasternode.o \
./rpcmining.o \
./rpcmisc.o \
./rpcnet.o \
./rpcprotocol.o \
./rpcrawtransaction.o \
./rpcserver.o \
./scheduler.o \
./sendalert.o \
./spork.o \
./sprint-cli.o \
./sprint-tx.o \
./sprintd.o \
./sync.o \
./timedata.o \
./torcontrol.o \
./txdb.o \
./txmempool.o \
./uint256.o \
./util.o \
./utilmoneystr.o \
./utilstrencodings.o \
./utiltime.o \
./validationinterface.o \
./versionbits.o 

CPP_DEPS += \
./activemasternode.d \
./addrman.d \
./alert.d \
./amount.d \
./arith_uint256.d \
./base58.d \
./bloom.d \
./chain.d \
./chainparams.d \
./chainparamsbase.d \
./checkpoints.d \
./clientversion.d \
./coins.d \
./compressor.d \
./core_read.d \
./core_write.d \
./darksend-relay.d \
./darksend.d \
./dbwrapper.d \
./dsnotificationinterface.d \
./governance-classes.d \
./governance-object.d \
./governance-vote.d \
./governance-votedb.d \
./governance.d \
./hash.d \
./httprpc.d \
./httpserver.d \
./init.d \
./instantx.d \
./keepass.d \
./key.d \
./keystore.d \
./main.d \
./masternode-payments.d \
./masternode-sync.d \
./masternode.d \
./masternodeconfig.d \
./masternodeman.d \
./merkleblock.d \
./miner.d \
./net.d \
./netbase.d \
./netfulfilledman.d \
./noui.d \
./pow.d \
./protocol.d \
./pubkey.d \
./random.d \
./rest.d \
./rpcblockchain.d \
./rpcclient.d \
./rpcgovernance.d \
./rpcmasternode.d \
./rpcmining.d \
./rpcmisc.d \
./rpcnet.d \
./rpcprotocol.d \
./rpcrawtransaction.d \
./rpcserver.d \
./scheduler.d \
./sendalert.d \
./spork.d \
./sprint-cli.d \
./sprint-tx.d \
./sprintd.d \
./sync.d \
./timedata.d \
./torcontrol.d \
./txdb.d \
./txmempool.d \
./uint256.d \
./util.d \
./utilmoneystr.d \
./utilstrencodings.d \
./utiltime.d \
./validationinterface.d \
./versionbits.d 


# Each subdirectory must supply rules for building sources it contributes
%.o: ../%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


